FROM openjdk:25-rc-jdk-slim AS build

RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml /app/

RUN keytool -genkeypair -alias springboot -keyalg RSA -keysize 2048 -dname "CN=localhost, OU=TI, O=Destino, L=SaoPaulo, ST=SP, C=BR" -storetype PKCS12 -keystore keystore.p12 -storepass WvbRQ9588@nMA2dMO -keypass WvbRQ9588@nMA2dMO -validity 3650 -ext "SAN=dns:localhost,ip:127.0.0.1,ip:::1"

COPY . /app/

RUN mvn clean install -DskipTests

FROM openjdk:25-rc-jdk-slim

WORKDIR /app

COPY --from=build /app/target/projeto-destino-SNAPSHOT.jar /app/projeto-destino.jar

COPY --from=build /app/keystore.p12 /app/keystore.p12

ENTRYPOINT ["java", "-jar", "projeto-destino.jar"]