FROM openjdk:25-rc-jdk-slim AS build

RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pom.xml /app/

RUN mvn dependency:resolve

COPY . /app/

RUN mvn clean install -DskipTests

FROM openjdk:25-rc-jdk-slim

WORKDIR /app

COPY --from=build /app/target/projeto-destino-SNAPSHOT.jar /app/projeto-destino.jar

ENTRYPOINT ["java", "-jar", "projeto-destino.jar"]