# Basic config
quarkus.application.name=destino
quarkus.http.host=localhost
quarkus.http.port=8080

# HTTPS
quarkus.tls.key-store.pem.0.cert=server.cert
quarkus.tls.key-store.pem.0.key=server.key

# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATABASE-URL}
quarkus.datasource.username=${DATABASE-USER}
quarkus.datasource.password=${DATABASE-PASSWORD}
%dev.quarkus.hibernate-orm.log.sql=true

# IBGE API URLs
ibge.regioes.url=https://servicodados.ibge.gov.br/api/v1/localidades/regioes
ibge.estados.url=https://servicodados.ibge.gov.br/api/v1/localidades/estados
ibge.cidades.url.template=https://servicodados.ibge.gov.br/api/v1/localidades/estados/%s/municipios

# Quarkus SmallRye JWT
mp.jwt.verify.issuer=https://localhost
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# Quarkus CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS-ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

# Test
%test.quarkus.http.insecure-requests=enabled