# Basic config
quarkus.application.name=destino
%dev.quarkus.http.host=localhost
quarkus.http.port=8080

# HTTPS
%dev.quarkus.tls.key-store.pem.0.cert=server.cert
%dev.quarkus.tls.key-store.pem.0.key=server.key

# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATABASE_URL}
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
%dev.quarkus.hibernate-orm.log.sql=true

# IBGE API URLs
# ibge.regioes.url=https://servicodados.ibge.gov.br/api/v1/localidades/regioes
# ibge.estados.url=https://servicodados.ibge.gov.br/api/v1/localidades/estados
# ibge.cidades.url.template=https://servicodados.ibge.gov.br/api/v1/localidades/estados/%s/municipios

# Quarkus SmallRye JWT
mp.jwt.verify.issuer=${JWT_ISSUER}
mp.jwt.verify.publickey=${PUBLIC_KEY}
smallrye.jwt.sign.key=${PRIVATE_KEY}

# Quarkus CORS
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS}
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

# Test
%test.quarkus.http.insecure-requests=enabled