# Basic config
spring.application.name=destino
spring.profiles.active=dev
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.enabled=true
spring.jpa.show-sql=true

# IBGE API URLs
ibge.regioes.url=https://servicodados.ibge.gov.br/api/v1/localidades/regioes
ibge.estados.url=https://servicodados.ibge.gov.br/api/v1/localidades/estados
ibge.cidades.url.template=https://servicodados.ibge.gov.br/api/v1/localidades/estados/%s/municipios